### ISSUE TITLE
Use vscode variable

### ISSUE THREAD

**Issue by Vince1024** [angus-mcritchie/custom-commands#1]
Hi,

Thanks for this great job.

is it possible to use vscode vars to build custom commands ?

Ex: 
        {
            "name": "Ping",
            "command": "ping ${selectedText}",
            "runOnStartup": false,
	    "runOnShutdown": false
        }

for me it don't seems to work.
Thanks.

**Comment by angus-mcritchie** [comment]
Hey @Vince1024,

Great suggestion mate!

VS Code doesn't have a nice API for the settings JSON variable parser, but there is an [open issue for it](https://github.com/microsoft/vscode/issues/46471).

Knowing this, I added this capability for `${selectedText}` and `${file}` (active text editor filename) and have published an update to the extension marketplace just now.

If you need any more variables, feel free to make a pull request 👍 

Cheers!

**Comment by Vince1024** [comment]
Many thanks, you're a boss !
