### ISSUE TITLE
Many thanks if ${folder} is supported.

### ISSUE THREAD

**Issue by yiqingpeng** [angus-mcritchie/custom-commands#2]

**Comment by angus-mcritchie** [comment]
Hey @yiqingpeng!

I can add that. Would that be the folder of the active file, the workspace folder, or something different?

One of these [VS Code variables](https://code.visualstudio.com/docs/editor/variables-reference), perhaps?

**Comment by yiqingpeng** [comment]
Sorry for confusing you. I mean the folder of the active file (i.e. VS variable ${fileDirname}), thank you.

**Comment by angus-mcritchie** [comment]
No problem, I just wanted to make sure I was adding the right one :)

I have just updated the package to v0.0.5 with the following variables.

- ${fileDirname}
- ${workspaceFolder}

Out of curiosity, what command are you planning on running with this new variable?

Thanks for your request, and build something awesome ❤️

**Comment by yiqingpeng** [comment]
Hi @angus-mcritchie , thanks for your work. It seems that this code does not work on Windows(has the path separator issue).
`'${folder}': vscode.window.activeTextEditor?.document.fileName.split('/').slice(0, -1).join('/'),`

**Comment by angus-mcritchie** [comment]
> Hi @angus-mcritchie , thanks for your work. It seems that this code does not work on Windows(has the path separator issue). `'${folder}': vscode.window.activeTextEditor?.document.fileName.split('/').slice(0, -1).join('/'),`

Oh, of course! I'm working inside WSL 2.

I have just updated it again to support multi-os separators :)

Let me know if you have any more issues or requests.

**Comment by yiqingpeng** [comment]
Nice updates. Thanks again!
